name = "ai-pun-generator"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[[routes]]
pattern = "/*"
script = ""

[build]
command = "npm run build"
output_dir = "dist"

# Enable CORS
[[headers]]
pattern = "/api/*"
[headers.response]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"

# Workers configuration
[workers_dev]
enabled = true

[env.production]
workers_dev = true